// DO NOT EDIT THIS FILE MANUALLY
// This file is modified by PlatformIO
// This file should not be pushed when modified, untrack changes with:
//  git update-index --assume-unchanged code/espurna/config/build.h
#define APP_BUILD_FLAGS ""
