/* Generated by re2c 4.3 */
#line 1 "espurna/bits_range.re"
/*

Part of UTILS MODULE

*/

#pragma once

#include "bits.h"
#include "types.h"
#include "utils.h"

namespace espurna {
namespace bits {

bool fill_range(Range& range, StringView view) {
    const char* YYCURSOR { view.begin() };
    const char* YYLIMIT { view.end() };

    bool done { false };
    bool out { false };

    auto last = -1;
    auto range_last = -1;

    ParseUnsignedResult result;
    int repeat { -1 };

    const char* p { nullptr };

loop:
    
#line 36 "espurna/bits_range.re.ipp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case ',': goto yy3;
		case '.': goto yy4;
		case '/': goto yy5;
		case '0' ... '9': goto yy6;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy10;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 68 "espurna/bits_range.re"
	{
        out = false;
        goto return_out;
      }
#line 57 "espurna/bits_range.re.ipp"
yy3:
	++YYCURSOR;
#line 59 "espurna/bits_range.re"
	{
        goto consume_last;
      }
#line 64 "espurna/bits_range.re.ipp"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy7;
		default: goto yy2;
	}
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy8;
		default: goto yy2;
	}
yy6:
	++YYCURSOR;
#line 41 "espurna/bits_range.re"
	{
        goto take_last;
      }
#line 83 "espurna/bits_range.re.ipp"
yy7:
	++YYCURSOR;
#line 55 "espurna/bits_range.re"
	{
        goto take_range;
      }
#line 90 "espurna/bits_range.re.ipp"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy8;
		default: goto yy9;
	}
yy9:
#line 45 "espurna/bits_range.re"
	{
        p = YYCURSOR - 1;
        while (*p != '/') {
          --p;
        }
        ++p;

        goto take_repeat;
      }
#line 108 "espurna/bits_range.re.ipp"
yy10:
#line 63 "espurna/bits_range.re"
	{
        done = true;
        goto consume_last;
      }
#line 115 "espurna/bits_range.re.ipp"
}
#line 73 "espurna/bits_range.re"


// update {last} with the latest digit
take_last:
    if (last == -1) {
      last = 0;
    }

    last = (last * 10) + (*(YYCURSOR - 1) - '0');
    goto loop;

// map every nth bit, based on repeat value
take_repeat:
    if (last == -1) {
        out = false;
        goto return_out;
    }

    if (repeat != -1) {
        out = false;
        goto return_out;
    }

    result = parseUnsigned(StringView(p, YYCURSOR), 10);
    if (!result.ok) {
        out = false;
        goto return_out;
    }

    repeat = result.value;

    goto consume_last;

// expect {last} to be set, bail otherwise
take_range:
    if (last == -1) {
        out = false;
        goto return_out;
    }

    range_last = last;
    last = -1;

    goto loop;

consume_last:
    // validate w/ range
    if ((last != -1) && !range.valid(last)) {
        out = false;
        goto return_out;
    }

    // in case repeat is set for a single value, set {last} to the last possible bit
    if ((range_last == -1) && (repeat > 0)) {
        range_last = last;
        last = range.end();
    }

    // fill output with {range_last}..{last} within range boundaries
    // bitset should support roll over for when {last} is less than {range_last}
    // meaning, 45..15 <=> 0..15,45..63. otherwise, support the usual 0..63
    // all bits between x and y, also including x and y, are set (i.e. range is inclusive)
    if ((last != -1) && (range_last != -1)) {
        range.fill(range_last, last, (repeat > 0) ? repeat : 1);
        out = true;
    // return immediately when there was no {last} after {range_last} was set
    } else if (range_last != -1) {
        done = true;
        out = false;
    // everything is ok, set and consume {last} bit
    } else if (last != -1) {
        range.set(last);
        out = true;
    // no need to continue, return current state
    } else {
        done = true;
    }

    if (done) {
        goto return_out;
    }

    last = range_last = -1;
    repeat = -1;

    goto loop;

return_out:
    return out;
}

} // namespace bits
} // namespace espurna
