/* Generated by re2c 4.3 */
#line 1 "espurna/ir_parse_simple.re"
/*

Part of the IR MODULE

For more info:
- https://re2c.org/
- https://re2c.org/manual/manual_c.html

*/

#pragma once

// TODO: some sanity checks for 'valid' ranges of the parsed values, when state machine reaches individual value decoders?

ParseResult<Payload> parse(StringView view) {
    const char* YYCURSOR { view.begin() };
    const char* YYLIMIT { view.end() };
    const char* YYMARKER;

    const char *p0 = nullptr, *p1 = nullptr;
    const char *c0 = nullptr, *c1 = nullptr;
    const char *b0 = nullptr, *b1 = nullptr;
    const char *r0 = nullptr, *r1 = nullptr;
    const char *s0 = nullptr, *s1 = nullptr;
    const char *d0 = nullptr, *d1 = nullptr;

    ParseResult<Payload> out;

    
#line 33 "espurna/ir_parse_simple.re.ipp"
const char *yyt1 { nullptr };
const char *yyt2 { nullptr };
const char *yyt3 { nullptr };
const char *yyt4 { nullptr };
const char *yyt5 { nullptr };
const char *yyt6 { nullptr };
#line 29 "espurna/ir_parse_simple.re"

    
#line 43 "espurna/ir_parse_simple.re.ipp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			yyt1 = YYCURSOR;
			goto yy3;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy36;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 63 "espurna/ir_parse_simple.re"
	{ goto return_out; }
#line 61 "espurna/ir_parse_simple.re.ipp"
yy3:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... ':': goto yy5;
		default: goto yy2;
	}
yy4:
	yych = *++YYCURSOR;
yy5:
	switch (yych) {
		case '0' ... '9': goto yy4;
		case ':': goto yy7;
		default: goto yy6;
	}
yy6:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy14;
		case 2: goto yy19;
		default: goto yy24;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f':
			yyt2 = YYCURSOR;
			goto yy8;
		default: goto yy6;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy9;
		default: goto yy6;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy10;
		case ':': goto yy11;
		default: goto yy6;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy12;
		case ':': goto yy11;
		default: goto yy6;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			yyt3 = YYCURSOR;
			goto yy13;
		default: goto yy6;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy15;
		case ':': goto yy11;
		default: goto yy6;
	}
yy13:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... '9': goto yy13;
		case ':': goto yy16;
		default: goto yy14;
	}
yy14:
	p0 = yyt1;
	c0 = yyt2;
	b0 = yyt3;
	p1 = yyt2;
	p1 -= 1;
	c1 = yyt3;
	c1 -= 1;
	b1 = YYCURSOR;
#line 43 "espurna/ir_parse_simple.re"
	{ goto update_out; }
#line 157 "espurna/ir_parse_simple.re.ipp"
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy17;
		case ':': goto yy11;
		default: goto yy6;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			yyt4 = YYCURSOR;
			goto yy18;
		default: goto yy6;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy20;
		case ':': goto yy11;
		default: goto yy6;
	}
yy18:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... '9': goto yy18;
		case ':': goto yy21;
		default: goto yy19;
	}
yy19:
	p0 = yyt1;
	c0 = yyt2;
	b0 = yyt3;
	r0 = yyt4;
	p1 = yyt2;
	p1 -= 1;
	c1 = yyt3;
	c1 -= 1;
	b1 = yyt4;
	b1 -= 1;
	r1 = YYCURSOR;
#line 48 "espurna/ir_parse_simple.re"
	{ goto update_out; }
#line 206 "espurna/ir_parse_simple.re.ipp"
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy22;
		case ':': goto yy11;
		default: goto yy6;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			yyt5 = YYCURSOR;
			goto yy23;
		default: goto yy6;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy25;
		case ':': goto yy11;
		default: goto yy6;
	}
yy23:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... '9': goto yy23;
		case ':': goto yy26;
		default: goto yy24;
	}
yy24:
	p0 = yyt1;
	c0 = yyt2;
	b0 = yyt3;
	r0 = yyt4;
	s0 = yyt5;
	p1 = yyt2;
	p1 -= 1;
	c1 = yyt3;
	c1 -= 1;
	b1 = yyt4;
	b1 -= 1;
	r1 = yyt5;
	r1 -= 1;
	s1 = YYCURSOR;
#line 54 "espurna/ir_parse_simple.re"
	{ goto update_out; }
#line 258 "espurna/ir_parse_simple.re.ipp"
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy27;
		case ':': goto yy11;
		default: goto yy6;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			yyt6 = YYCURSOR;
			goto yy28;
		default: goto yy6;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy30;
		case ':': goto yy11;
		default: goto yy6;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy28;
		default: goto yy29;
	}
yy29:
	p0 = yyt1;
	c0 = yyt2;
	b0 = yyt3;
	r0 = yyt4;
	s0 = yyt5;
	d0 = yyt6;
	p1 = yyt2;
	p1 -= 1;
	c1 = yyt3;
	c1 -= 1;
	b1 = yyt4;
	b1 -= 1;
	r1 = yyt5;
	r1 -= 1;
	s1 = yyt6;
	s1 -= 1;
	d1 = YYCURSOR;
#line 61 "espurna/ir_parse_simple.re"
	{ goto update_out; }
#line 311 "espurna/ir_parse_simple.re.ipp"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy31;
		case ':': goto yy11;
		default: goto yy6;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy32;
		case ':': goto yy11;
		default: goto yy6;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy33;
		case ':': goto yy11;
		default: goto yy6;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy34;
		case ':': goto yy11;
		default: goto yy6;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'F':
		case 'a' ... 'f': goto yy35;
		case ':': goto yy11;
		default: goto yy6;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy11;
		default: goto yy6;
	}
yy36:
#line 64 "espurna/ir_parse_simple.re"
	{ goto return_out; }
#line 366 "espurna/ir_parse_simple.re.ipp"
}
#line 65 "espurna/ir_parse_simple.re"


update_out:
    {
        if (!((c1 - c0) % 2)) {
            out = prepare(
                StringView{p0, p1},
                StringView{c0, c1},
                StringView{b0, b1},
                StringView{r0, r1},
                StringView{s0, s1},
                StringView{d0, d1});
        }
    }

return_out:
    return out;
}
