/* Generated by re2c 4.3 */
#line 1 "espurna/led_parse.re"
/*

LED MODULE

Copyright (C) 2020-2021 by Maxim Prokhorov <prokhorov dot max at outlook dot com>

*/

#pragma once

#include "utils.h"
#include "led.h"
#include "led_pattern.ipp"

namespace espurna {
namespace led {
namespace {

using ParseDuration = espurna::duration::Milliseconds;

using DurationPair = espurna::duration::Pair;
using ParseResult = espurna::duration::PairResult;

Duration native_duration(DurationPair pair) {
    using namespace espurna::duration;
    return to_chrono<Duration>(pair);
}

Duration native_duration(ParseResult result) {
    return result.ok
        ? native_duration(result.value)
        : Duration::min();
}

ParseResult parse_time(StringView view) {
    using namespace espurna::duration;
    return parse(view, ParseDuration::period{});
}

static constexpr auto RepeatsMax = size_t{ 255 };

// Scans input string with format
// '<on1>,<off1>,<repeats1> <on2>,<off2>,<repeats2> ...'
// And returns a list of Delay objects for the pattern

Pattern parse(StringView value) {
    Pattern out;

    StringView tmp;

    const char* p1;
    const char* p2;
    const char* p3;

    const char* YYCURSOR { value.begin() };
    const char* YYLIMIT { value.end() };
    const char* YYMARKER;

loop:
#line 63 "espurna/led_parse.re.ipp"
const char *yyt1;const char *yyt2;const char *yyt3;
#line 60 "espurna/led_parse.re"


#line 68 "espurna/led_parse.re.ipp"
	{
		char yych;
		yych = (char)*YYCURSOR;
		switch (yych) {
			case '\t' ... '\v':
			case '\r':
			case ' ': goto yy3;
			case '0' ... '9':
				yyt1 = YYCURSOR;
				goto yy5;
			default:
				if (YYLIMIT <= YYCURSOR) goto yy17;
				goto yy1;
		}
yy1:
		++YYCURSOR;
yy2:
#line 76 "espurna/led_parse.re"
		{ goto return_out; }
#line 88 "espurna/led_parse.re.ipp"
yy3:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case '\t' ... '\v':
			case '\r':
			case ' ': goto yy3;
			default: goto yy4;
		}
yy4:
#line 78 "espurna/led_parse.re"
		{ goto loop; }
#line 100 "espurna/led_parse.re.ipp"
yy5:
		yych = (char)*(YYMARKER = ++YYCURSOR);
		switch (yych) {
			case ',': goto yy6;
			case '0' ... '9': goto yy8;
			case 'A' ... 'z': goto yy9;
			default: goto yy2;
		}
yy6:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case '0' ... '9':
				yyt2 = YYCURSOR;
				goto yy10;
			default: goto yy7;
		}
yy7:
		YYCURSOR = YYMARKER;
		goto yy2;
yy8:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy6;
			case '0' ... '9': goto yy8;
			case 'A' ... 'z': goto yy9;
			default: goto yy7;
		}
yy9:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy6;
			case 'A' ... 'z': goto yy11;
			default: goto yy7;
		}
yy10:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy12;
			case '0' ... '9': goto yy10;
			case 'A' ... 'z': goto yy14;
			default: goto yy7;
		}
yy11:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy6;
			default: goto yy7;
		}
yy12:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case '0' ... '9':
				yyt3 = YYCURSOR;
				goto yy15;
			default:
				yyt3 = NULL;
				goto yy13;
		}
yy13:
		p1 = yyt1;
		p2 = yyt2;
		p3 = yyt3;
#line 80 "espurna/led_parse.re"
		{
            tmp = StringView(p1, p2 - p1 - 1);
            const auto on = parse_time(tmp);
            if (!on.ok) {
                goto return_out;
            }
            
            tmp = StringView(p2, p3 - p2 - 1);
            const auto off = parse_time(tmp);
            if (!off.ok) {
                goto return_out;
            }

            size_t repeats_value;
            if (p3) {
                tmp = StringView(p3, YYCURSOR);
                const auto repeats = parseUnsigned(tmp, 10);
                if (!repeats.ok) {
                    goto return_out;
                }
                repeats_value = repeats.value;
            } else {
                repeats_value = 0;
            }

            repeats_value = std::min(repeats_value, RepeatsMax);

            out.add(
                native_duration(on),
                native_duration(off),
                repeats_value);
            if (repeats_value) {
                goto loop;
            }
        }
#line 199 "espurna/led_parse.re.ipp"
yy14:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy12;
			case 'A' ... 'z': goto yy16;
			default: goto yy7;
		}
yy15:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case '0' ... '9': goto yy15;
			default: goto yy13;
		}
yy16:
		yych = (char)*++YYCURSOR;
		switch (yych) {
			case ',': goto yy12;
			default: goto yy7;
		}
yy17:
#line 75 "espurna/led_parse.re"
		{ goto return_out; }
#line 222 "espurna/led_parse.re.ipp"
	}
#line 115 "espurna/led_parse.re"


return_out:
    return out;
}

} // namespace
} // namespace led
} // namespace espurna
